default[:icinga][:version] = "1.3.1"
default[:icinga][:checksum] = "b6eec308"
default[:icinga][:email] = "nobody@example.com"
default[:icinga][:web][:version] = "1.3.1"
default[:icinga][:web][:checksum] = "76167632"
